services:
  - type: web
    name: rainier-chatbot-api
    env: node
    buildCommand: npm run render-deploy
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5500
      - key: MONGO_URL
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: ACCESS_TOKEN_SECRET
        sync: false
      - key: CLIENT_URL
        value: https://stieve-chatbot.vercel.app
    healthCheckPath: /health
